### ISSUE TITLE
no more "no-thread" branch of Unicorn

### ISSUE THREAD

**Issue by aquynh** [cseagle/sk3wldbg#1]
the "no-thread" branch of Unicorn was merged into the "master" branch, and got deleted. please update your README, thanks.

**Comment by cseagle** [comment]
Thanks for the heads up.

**Comment by jakesays** [comment]
Does this mean we should be using upstream unicorn?

**Comment by cseagle** [comment]
No, per the updated readme, you now need to use my ram_addr branch of unicorn.
