### ISSUE TITLE
Use plugins on arch linux

### ISSUE THREAD

**Issue by dummys** [cseagle/sk3wldbg#3]
Hello,

Trying to make it work under arch linux with latest 6.9 ida without luck.
Using the pre-built binary and puting libunicorn.so.1 in /usr/lib, also trying to put libida.so/libida64.so to /usr/lib, then ldconfig.
log:

-> $ sudo ldd libunicorn.so.1     
	linux-gate.so.1 (0xf77c8000)
	libglib-2.0.so.0 => /usr/lib32/libglib-2.0.so.0 (0xf6dcf000)
	libm.so.6 => /usr/lib32/libm.so.6 (0xf6d7a000)
	libc.so.6 => /usr/lib32/libc.so.6 (0xf6bc5000)
	libpcre.so.1 => /usr/lib32/libpcre.so.1 (0xf6b50000)
	libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf6b32000)
	/usr/lib/ld-linux.so.2 (0x565e5000)

-> $ ldd sk3wldbg.plx64 
	linux-gate.so.1 (0xf7730000)
	libida64.so => /usr/lib/libida64.so (0xf73e3000)
	libunicorn.so.1 => /usr/lib/libunicorn.so.1 (0xf6b40000)
	libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xf69c9000)
	libm.so.6 => /usr/lib32/libm.so.6 (0xf6974000)
	libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf6959000)
	libc.so.6 => /usr/lib32/libc.so.6 (0xf67a4000)
	libdl.so.2 => /usr/lib32/libdl.so.2 (0xf679f000)
	librt.so.1 => /usr/lib32/librt.so.1 (0xf6796000)
	libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf6779000)
	libglib-2.0.so.0 => /usr/lib32/libglib-2.0.so.0 (0xf6650000)
	/usr/lib/ld-linux.so.2 (0x56620000)
	libpcre.so.1 => /usr/lib32/libpcre.so.1 (0xf65db000)

Is there any message when the plugin successfuly loaded in IDA ? I can't see any debugger called sk3wldbg on an arm binary.

What can I do to debug it ?
Thanks

**Comment by cseagle** [comment]
The plugin usually spits messages to IDA's output window, Can you paste the contents of your output windows following opening an ARM binary? Are you running idaq or idaq64?

**Comment by dummys** [comment]
There is no weird message in the output.
idaq.

**Comment by cseagle** [comment]
If you are using idaq, you need sk3wldbg.plx, NOT sk3wldbg.plx64 (which is what you reference in your original message). Has sk3wldbg.plx also been copied into your IDA plugins directory?

**Comment by dummys** [comment]
yes exactly the same as the 64 one.  Using pre built bins.

**Comment by cseagle** [comment]
If you strace the launch of ida, what "open" calls are being made and do any of them fail with EEXIST?

**Comment by dummys** [comment]
No there is no EEXIST in the log.

**Comment by dummys** [comment]
Any idea then ? Still stuck...

**Comment by cseagle** [comment]
No ideas without additional info. Are you willing to share a complete strace of launching idaq on your system?

**Comment by dummys** [comment]
there you go: https://bpaste.net/show/b3229c0cfd2b

**Comment by dummys** [comment]
didn't know what I give you more... Ida is making logs too ?

**Comment by cseagle** [comment]
IDA does logging if you set the environment variable IDALOG=<filepath> before launching IDA.

In your pastebin beginning at line 2648, continuing through line 2682, you can see IDA iterate over your installed plugins. None of these seem to be sk3wldbg.plx. There is no evidence that sk3wldbg is installed in /opt/ida-6.9/plugins on your system.

**Comment by dummys** [comment]
omfg... I just looked and in fact i've keep the folder with the two plugins inside. Removing the folder and puting the plugins seems to load it. Sorry for such big mistake...
