### ISSUE TITLE
trying to use the dbg under windows

### ISSUE THREAD

**Issue by dummys** [cseagle/sk3wldbg#4]
Hi,

Got an error when trying to use the dbg plugin under windows.
I put the unicorn1.dll in IDA directory and put both .plw, .p64 in the plugins directory.
Grabbed  libglib-2.0-0.dll, libintl-8.dll, libgcc_s_dw2-1.dll, from Qemu and put them in the IDA directory as well. When running Ida I get: LoadLibrary(C:\Program files\ida\plugins\sk3wldbg_user.plw) error: The specified module could not be found.

What is wrong in my installation ?
Latest ida of course.

**Comment by cseagle** [comment]
I just updated the readme, there are a few transitive dependencies that were not listed. Please make sure you have all of: libglib-2.0-0.dll, libintl-8.dll, libgcc_s_dw2-1.dll, libwinpthread-1.dll, libiconv-2.dll.

**Comment by dummys** [comment]
Yes I put it on IDADIR, still same error. How can I debug it ?

**Comment by dummys** [comment]
Your version is working on windows ? Or you use it under linux ?

**Comment by cseagle** [comment]
It works for me on Windows 7, Linux, and Mac

**Comment by cseagle** [comment]
Are you getting any messages in IDA's output window related to sk3wldbg?

**Comment by dummys** [comment]
Yes i'm getting a "The Specified procedure could not be found."

**Comment by dummys** [comment]
Ok so at the end I made your stuff works. Please update the documentation to tell windows user to download and install TDM-GCC.
http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm64-gcc-5.1.0-2.exe/download

This is the only one where I found working DLL's.

**Comment by dummys** [comment]
When launching the debuggers on any binary I get a crash on unicorn1.dll.

Did you try to use it under windows 7 x64 but ida 32bit version idaq.exe ?
how can I debug this error ?

**Comment by cseagle** [comment]
I run the debugger routine on Win 7 x64 with idaq and no problems. Did you ever try installing the Msys libraries per the readme?

**Comment by dummys** [comment]
So what I've done so far:

I'm on a deconnected workstation, so I use the latest Cygwin setup_x86.exe to do a download only.
Iselected in the package list the same package you put on the readme: make gcc-core pkg-config libpcre-devel zlib-devel libglib2.0-devel
I tried with the setup_x86_x64.exe also.

But with Cygwin, there is no dll called libglib-2.0-0.dll, libintl-8.dll, libgcc_s_dw2-1.dll, libwinpthread-1.dll, libiconv-2.dll. So for me it's not good. Then I tried TDM-GCC where I finally found the lib, puting the lib in IDADIR folder with unicorn1.dll and launching IDA, I get the result I shown to you.

The best would be to show the exact url of your source and how you install it.
Because with cygwin is definitely not working.

**Comment by dummys** [comment]
no news ?

**Comment by dummys** [comment]
Can you post how you get all lib under windows ?

**Comment by dummys** [comment]
Following exactly your stuff on a internet connected computer:

download latest cygwin64, installed, then install the apt-cyg script and:
putting c:\Cygwin64\bin in the PATH.
apt-cyg install make gcc-core pkg-config libpcre-devel zlib-devel libglib2.0-devel

Result: sk3wldbg: the specified module could not be found.

There is really a problem in your readme.

**Comment by dummys** [comment]
Finally got it working with Msys2. Do not use this fucking Cygwin, it's useless and it didn't work with the latest version.
