### ISSUE TITLE
Issue when Building with VS 2015

### ISSUE THREAD

**Issue by robinchrist** [cseagle/sk3wldbg#9]
Hey there,
Building sk3wldbg on Visual Studio (Community) 2015 fails (both 32 and 64bit)

Error:
`1>sk3wldbg.cpp(1378): error C2440: "=": "int (__stdcall *)(pid_t,int,int)" kann nicht in "int (__stdcall *)(pid_t,int)" konvertiert werden`

Plus the following warnings
`1>D:\idaplus\idasdk68\include\typeinf.hpp(2606): warning C4267: "return": Konvertierung von "size_t" nach "type_t", Datenverlust möglich
1>D:\idaplus\idasdk68\include\typeinf.hpp(2639): warning C4267: "return": Konvertierung von "size_t" nach "uchar", Datenverlust möglich
1>D:\idaplus\idasdk68\include\typeinf.hpp(2829): warning C4267: "return": Konvertierung von "size_t" nach "cm_t", Datenverlust möglich
1>D:\idaplus\idasdk68\include\typeinf.hpp(2891): warning C4267: "return": Konvertierung von "size_t" nach "type_t", Datenverlust möglich
1>  sk3wldbg.cpp(1378): note: Diese Konvertierung erfordert einen reinterpret_cast-Operator oder eine Typumwandlung im C- oder Funktionsformat`

I'm not enough into this API to submit a fix...

**Comment by cseagle** [comment]
The error should be fixed with commit d653120. The warnings are issues in an SDK header that would need to be fixed by the Hex-Rays people.
